services:
  lab03-cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab03-cron
    env_file:
      - .env
    environment:
      - TZ=Europe/Chisinau
    volumes:
      - ./data:/app/data
      - ./logs:/var/log
    restart: unless-stopped
